$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
display_name: lab02-train-uri-folder
experiment_name: lab02-data-and-job
compute: azureml:cpu-cluster
code: ../src
environment:
  image: mcr.microsoft.com/azureml/openmpi5.0-ubuntu24.04:latest
  conda_file: ../src/conda.yml

command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --asset_type uri_folder

inputs:
  training_data:
    type: uri_folder
    path: azureml:telco-churn-folder:1
    mode: ro_mount
